dailyschedule/urls.py
from django.urls import path

from . import views

app_name='cronograma'
urlpatterns = [
    path('', views.index, name='index'),
    path('dailyschedule/<int:pk>/', views.detalhes.as_view(), name='detalhes'),
    path('dailyschedule/cadastrar/', views.gerarCronograma, name='gerarCronograma'),
    path('dailyschedule/criar-cronograma/', views.criarCronograma, name='criarCronograma'),
    path('dailyschedule/info/', views.criarInfo.as_view(), name='criarInfo'),
    path('dailyschedule/aulas/', views.criarAulas.as_view(), name='criarAulas'),
    path('dailyschedule/materias/', views.criarMaterias.as_view(), name='criarMaterias'),
    path('dailyschedule/provas/', views.criarProvas.as_view(), name='criarProvas'),
    path('dailyschedule/afazer/', views.criarAfazer.as_view(), name='criarAfazer'),
    path('dailyschedule/horario-vago/', views.criarHVago.as_view(), name='criarHVago'),


    path('dailyschedule/entrar/', views.Login.as_view(), name='Login'),
    path('dailyschedule/cadastro/', views.Cadastrar.as_view(), name='Cadastrar'),
    path('dailyschedule/logout/', views.Logout, name='Logout'),

    path('dailyschedule/meus-cronogramas/', views.meusCronogramas.as_view(), name='meusCronogramas'),

    path('dailyschedule/editar/<int:pk>/', views.editarCronograma.as_view(), name='editarCronograma'),
    path('dailyschedule/HabEditar/<int:pk>/', views.HabEditar.as_view(), name='HabEditar'),
    path('dailyschedule/excluirCronograma/<int:pk>/', views.excluirCronograma.as_view(), name='excluirCronograma'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dailyschedule.urls')),
]

dailyschedule/models.py
from django.db import models

from django.db import models
from django.utils import timezone
import datetime

class Aluno(models.Model):
    nome = models.CharField(max_length=30)
    usuario = models.CharField(max_length=30)
    senha = models.CharField(max_length=30)

    def __str__(self):
        return self.usuario

class Cronograma(models.Model):
    privacidade = models.BooleanField(default = False)
    titulo = models.CharField(max_length=100)
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)

    def __str__(self):
        return ("{0} - {1}").format(self.titulo, self.aluno)

class Tarefa(models.Model):
    titulo = models.CharField(max_length=50)
    assunto = models.CharField(max_length=50, null=True)
    descricao = models.CharField(max_length=100)
    hora_inicio = models.TimeField(default=timezone.now)
    hora_fim = models.TimeField(null=True)
    data = models.DateTimeField('Data Cronograma')
    status = models.BooleanField(default=False)
    cronograma = models.ForeignKey(Cronograma, on_delete=models.CASCADE)

    def desta_semana(self):
        now = datetime.date.today()
        week= now.isocalendar().week()
        week_trf= self.data.isocalendar().week()
        return (week_trf == week)

    def __str__(self):
        return self.descricao

class Tipo(models.Model):
    nome = models.CharField(max_length=12)
    tarefa = models.ForeignKey(Tarefa, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

dailyschedule/views.py
import datetime
#from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View

from .models import Cronograma, Aluno, Tarefa


def index(request):
    search = request.GET.get('search')
    if search:
        return busca(request)
    return render(request, 'dailyschedule/index.html')

def busca(request):
    latest_ds_list = Cronograma.objects.all()
    search = request.GET.get('search')
    if search:
        latest_ds_list = latest_ds_list.filter(titulo__icontains=search)
    context = {'latest_ds_list': latest_ds_list}
    return render(request, 'dailyschedule/busca.html', context)

class detalhes(View):
    def get(self, request, *args, **kwargs):
        cronograma = get_object_or_404(Cronograma, pk=kwargs['pk'])
        tarefas = self.tarefas_da_semana(cronograma)
        contexto = {'cronograma':cronograma, 'tarefas':tarefas}

        return render(request, 'dailyschedule/detalhes.html',contexto)

    def tarefas_da_semana(self, cronograma):
        tarefas = Tarefa.objects.all()
        inicio = self.getInicio()
        fim = inicio + datetime.timedelta(days=7)
        ##return Tarefa.objects.all().order_by('data')
        #return Tarefa.objects.filter(data__week_day__gt=inicio).filter(data__week_day__lte=fim).order_by('data')
        return Tarefa.objects.filter(cronograma=cronograma).filter(data__gt=inicio).filter(data__lte=fim).order_by('data')
        #return Tarefa.objects.filter(cronograma=cronograma).filter(data_isocalendar()[1]==inicio_isocalendar()[1]).filter(data_isocalendar()[1]==fim_isocalendar()).order_by('data')

    def getInicio(self):
        now = datetime.date.today()
        inicio = now
        if now.weekday == 1:
            inicio = now - datetime.timedelta(days=1)
        elif now.weekday == 2:
            inicio = now - datetime.timedelta(days=2)
        elif now.weekday == 3:
            inicio = now - datetime.timedelta(days=3)
        elif now.weekday == 4:
            inicio = now - datetime.timedelta(days=4)
        elif now.weekday == 5:
            inicio = now - datetime.timedelta(days=5)
        elif now.weekday == 6:
            inicio = now - datetime.timedelta(days=6)
        return inicio

    def getFim(self):
        now = datetime.date.today()
        fim = now
        if now.weekday == 0:
            fim = now + datetime.timedelta(days=6)
        elif now.weekday == 1:
            fim = now + datetime.timedelta(days=5)
        elif now.weekday == 2:
            fim = now + datetime.timedelta(days=4)
        elif now.weekday == 3:
            fim = now + datetime.timedelta(days=3)
        elif now.weekday == 4:
            fim = now + datetime.timedelta(days=2)
        elif now.weekday == 5:
            fim = now + datetime.timedelta(days=1)
        return fim


def gerarCronograma(request):
    return render(request, 'dailyschedule/gerarCronograma.html')

def criarCronograma(request):
    try:
        if request.session['id_user']:
            search = request.GET.get('search')
            if search:
                return busca(request)
            return render(request, 'dailyschedule/criar-cronograma.html')
    except:
        return render(request, 'dailyschedule/index.html')


class criarInfo(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'dailyschedule/info.html')

    def post(self, request, *args, **kwargs):
        titulo_cronograma = request.POST['titulo_cronograma']
        aluno = get_object_or_404(Aluno, pk=request.session['id_user'])
        cronograma = Cronograma(titulo=titulo_cronograma, aluno = aluno)

        privacidade = request.POST.getlist('priv')
        for priv in privacidade:
            if priv=='1':
                cronograma.privacidade=True

            elif priv=='2':

                cronograma.privacidade=False
            else:
                erro = 'Dados inválidos!'
                return render(request, 'dailyschedule/criar-cronograma.html',{'msg-erro': erro})

        cronograma.save()
        request.session['cronograma'] = cronograma.id
        return render(request, 'dailyschedule/criar-cronograma.html')

class criarAulas(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'dailyschedule/aulas.html')

    def post(self, request, *args, **kwargs):
        cronograma = get_object_or_404(Cronograma, pk=request.session['cronograma'])
        i = 1
        name = 'titulo_aula_'
        try:
            while request.POST[f'{name}{i}']:
                aula = Tarefa(titulo=request.POST['titulo_aula_'+str(i)],
                descricao = request.POST['descricao_aula_'+str(i)], hora_inicio=request.POST['horario_inicio_aula_'+str(i)],
                hora_fim=request.POST['horario_fim_aula_'+str(i)], data=request.POST['data_aula_'+str(i)], cronograma = cronograma)
                aula.save()
                i=i+1
        except:
            return render(request, 'dailyschedule/criar-cronograma.html')

        return render(request, 'dailyschedule/criar-cronograma.html')

class criarMaterias(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'dailyschedule/materias.html')

    def post(self, request, *args, **kwargs):
        cronograma = get_object_or_404(Cronograma, pk=request.session['cronograma'])
        i = 1
        name = 'titulo_materia_'
        try:
            while request.POST[f'{name}{i}']:
                materia = Tarefa(titulo=request.POST['titulo_materia_'+str(i)], assunto=request.POST['assunto_'+str(i)],
                descricao = request.POST['descricao_materia_'+str(i)], hora_inicio=request.POST['horario_inicio_materia_'+str(i)],
                hora_fim=request.POST['horario_fim_materia_'+str(i)], data=request.POST['data_materia_'+str(i)], cronograma = cronograma)
                materia.save()
                i=i+1
        except:
            return render(request, 'dailyschedule/criar-cronograma.html')       
        return render(request, 'dailyschedule/criar-cronograma.html')

class criarProvas(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'dailyschedule/provas.html')

    def post(self, request, *args, **kwargs):
        cronograma = get_object_or_404(Cronograma, pk=request.session['cronograma'])
        i = 1
        name = 'titulo_prova_'
        try:
            while request.POST[f'{name}{i}']:
                prova = Tarefa(titulo=request.POST['titulo_prova_'+str(i)], assunto=request.POST['assunto_'+str(i)],
                descricao = request.POST['descricao_prova_'+str(i)], hora_inicio=request.POST['horario_inicio_prova_'+str(i)],
                hora_fim=request.POST['horario_fim_prova_'+str(i)], data=request.POST['data_prova_'+str(i)], cronograma = cronograma)
                prova.save()
                i=i+1
        except:
            return render(request, 'dailyschedule/criar-cronograma.html')
        return render(request, 'dailyschedule/criar-cronograma.html')

class criarAfazer(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'dailyschedule/afazeres.html')

    def post(self, request, *args, **kwargs):
        cronograma = get_object_or_404(Cronograma, pk=request.session['cronograma'])
        i = 1
        name = 'titulo_afazer_'
        try:
            while request.POST[f'{name}{i}']:
                afazer = Tarefa(titulo=request.POST['titulo_afazer_'+str(i)],
                descricao = request.POST['descricao_afazer_'+str(i)], hora_inicio=request.POST['horario_inicio_afazer_'+str(i)],
                hora_fim=request.POST['horario_fim_afazer_'+str(i)], data=request.POST['data_afazer_'+str(i)], cronograma = cronograma)
                afazer.save()
                i=i+1
        except:
            return render(request, 'dailyschedule/criar-cronograma.html')
        return render(request, 'dailyschedule/criar-cronograma.html')

class criarHVago(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'dailyschedule/hvago.html')

    def post(self, request, *args, **kwargs):
        cronograma = get_object_or_404(Cronograma, pk=request.session['cronograma'])
        i = 1
        name = 'titulo_hvago_'
        del request.session['cronograma']
        tarefas = self.tarefas_da_semana(cronograma)
        contexto = {'cronograma':cronograma,'tarefas':tarefas}
        try:
            while request.POST[f'{name}{i}']:
                hvago = Tarefa(titulo=request.POST['titulo_hvago_'+str(i)],
                descricao = request.POST['descricao_hvago_'+str(i)], hora_inicio=request.POST['horario_inicio_hvago_'+str(i)],
                hora_fim=request.POST['horario_fim_hvago_'+str(i)], data=request.POST['data_hvago_'+str(i)], cronograma = cronograma)
                hvago.save()
                i=i+1
        except:
            return render(request, 'dailyschedule/detalhes.html',contexto)
        return render(request, 'dailyschedule/detalhes.html',contexto)

    def tarefas_da_semana(self, cronograma):
        tarefas = Tarefa.objects.all()
        inicio = self.getInicio()
        fim = inicio + datetime.timedelta(days=7)
        return Tarefa.objects.filter(cronograma=cronograma).filter(data__gt=inicio).filter(data__lte=fim).order_by('data')

    def getInicio(self):
        now = datetime.date.today()
        inicio = now
        if now.weekday == 1:
            inicio = now - datetime.timedelta(days=1)
        elif now.weekday == 2:
            inicio = now - datetime.timedelta(days=2)
        elif now.weekday == 3:
            inicio = now - datetime.timedelta(days=3)
        elif now.weekday == 4:
            inicio = now - datetime.timedelta(days=4)
        elif now.weekday == 5:
            inicio = now - datetime.timedelta(days=5)
        elif now.weekday == 6:
            inicio = now - datetime.timedelta(days=6)
        return inicio

dailyschedule/templates/dailyschedule/afazeres.html
<section id="criar-crono1">
  <form class="crono-info1" action="{% url 'cronograma:criarAfazer' %}" method="post">
    {% csrf_token %}

        <div style="display:flex; gap:10px; flex-direction:column;">

            <div style="display:flex; gap:10px; margin-bottom:15px;">

            <div class="info">
              <label for="aulas">Informe seus afazeres</label>
              <input type="text" name="titulo_afazer_1" id="titulo_afazer_1" />
            </div>
            <div class="info">
              <label for="horario">Início</label>
              <input type="time" name="horario_inicio_afazer_1" id="horario_inicio_afazer_1" />
            </div>
            <div class="info">
              <label for="horario">Término</label>
              <input type="time" name="horario_fim_afazer_1" id="horario_fim_afazer_1" />
            </div>
            <div class="info">
              <label for="datas">Datas</label>
              <input type="date" name="data_afazer_1" id="data_afazer_1" />
            </div>


            <label id="add_address" onclick="addClassLine()" style="font-size:50pt;">+</label>
            </div>

            <div id="adress" style="paddin:50px 50px;">

            </div>

        </div>
        <button type="submit" class="btncont" >Salvar afazeres</button>
  </form>
</section>

dailyschedule/templates/dailyschedule/aulas.html
<section id="criar-crono1">
  <form class="crono-info1" action="{% url 'cronograma:criarAulas' %}" method="post">
     {% csrf_token %}
    <div style="display:flex; gap:10px; flex-direction:column;">

        <div style="display:flex; gap:10px; margin-bottom:15px;">

            <div class="info">
              <label for="aulas">Informe suas aulas</label>
              <input type="text" name="titulo_aula_1" id="titulo_aula_1" />
            </div>
            <div class="info">
              <label for="aulas">Descrição</label>
              <input type="text" name="descricao_aula_1" id="descricao_aula_1" />
            </div>
            <div class="info">
              <label for="horario">Início</label>
              <input type="time" name="horario_inicio_aula_1" id="horario_inicio_1" />
            </div>
            <div class="info">
              <label for="horario">Término</label>
              <input type="time" name="horario_fim_aula_1" id="horario_fim_1" />
            </div>
            <div class="info">
              <label for="datas">Datas</label>
              <input type="date" name="data_aula_1" id="data_aula_1" />
            </div>

            <label id="add_address" onclick="addClassLine()" style="font-size:50pt;">+</label>
            </div>
            <div id="adress" style="paddin:50px 50px;">

            </div>
            </div>

            <button type="submit" class="btncont" >Salvar aulas</button>
        </form>
    </section>

dailyschedule/templates/dailyschedule/gerarCronograma.html
<!DOCTYPE html>
<html>

<head>
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Abhaya+Libre&display=swap" rel="stylesheet" />
    <link href="./css/main.css" rel="stylesheet" />
    <link href="./css/style.css" rel="stylesheet" />

    <title>Cria-01</title>

</head>

<body>
    <div class="v54_127">
        <form action="{% url 'cronograma:gerarCronograma' %}" method="post">
        {% csrf_token %}

        <label for="horario">Insira o nome do seu cronograma: </label>
        <input type="text" name="titulo_cronograma" id="titulo_cronograma">
        <div class="crono-priv">
        <label for="privacidade">Quer que seu cronograma seja visível para outras pessoas?</label> <br> <br>
        <input type="radio" name="priv" id="publico">
        <label for="priv">Quero que seja público</label>
        <input type="radio" name="priv" id="privado">
        <label for="priv">Quero que seja privado</label>
        </div>

        <div class="info">
          <label for="aulas">Informe suas aulas</label>
          <input type="text" name="titulo_aula_1" id="titulo_aula_1" />
        </div>
        <div class="info">
          <label for="aulas">Descrição</label>
          <input type="text" name="descricao_aula_1" id="descricao_aula_1" />
        </div>
        <div class="info">
          <label for="horario">Início</label>
          <input type="time" name="horario_inicio_aula_1" id="horario_inicio_1" />
        </div>
        <div class="info">
          <label for="horario">Término</label>
          <input type="time" name="horario_fim_aula_1" id="horario_fim_1" />
        </div>
        <div class="info">
          <label for="datas">Datas</label>
          <input type="date" name="data_aula_1" id="data_aula_1" />
        </div><br>

        <div class="info">
          <label for="titulo_materia_1">Informe suas matérias</label>
          <input type="text" name="titulo_materia_1" id="titulo_materia_1" />
        </div>
        <div class="info">
          <label for="assunto_1">Assunto</label>
          <input type="text" name="assunto_1" id="assunto_1" />
        </div>
        <div class="info">
          <label for="descricao_materia_1">Descrição</label>
          <input type="text" name="descricao_materia_1" id="descricao_materia_1" />
        </div>
        <div class="info">
          <label for="horario_inicio_materia_1">Início</label>
          <input type="time" name="horario_inicio_materia_1" id="horario_inicio_materia_1" />
        </div>
        <div class="info">
          <label for="horario">Término</label>
          <input type="time" name="horario_fim_materia_1" id="horario_fim_materia_1" />
        </div>
        <div class="info">
          <label for="datas">Datas</label>
          <input type="date" name="data_materia_1" id="data_materia_1" />
        </div>

        <div class="info">
          <label for="aulas">Informe suas provas</label>
          <input type="text" name="titulo_prova_1" id="titulo_prova_1" />
        </div>
        <div class="info">
          <label for="aulas">Descrição</label>
          <input type="text" name="descricao_prova_1" id="descricao_prova_1" />
        </div>
        <div class="info">
          <label for="horario">Início</label>
          <input type="time" name="horario_inicio_prova_1" id="horario_inicio_prova_1" />
        </div>
        <div class="info">
          <label for="horario">Término</label>
          <input type="time" name="horario_fim_prova_1" id="horario_fim_prova_1" />
        </div>
        <div class="info">
          <label for="datas">Datas</label>
          <input type="date" name="data_prova_1" id="data_prova_1" />
        </div>

        <div class="info">
          <label for="aulas">Informe seus afazeres</label>
          <input type="text" name="titulo_afazer_1" id="titulo_afazer_1" />
        </div>
        <div class="info">
          <label for="aulas">Descrição</label>
          <input type="text" name="descricao_afazer_1" id="descricao_afazer_1" />
        </div>
        <div class="info">
          <label for="horario">Início</label>
          <input type="time" name="horario_inicio_afazer_1" id="horario_inicio_afazer_1" />
        </div>
        <div class="info">
          <label for="horario">Término</label>
          <input type="time" name="horario_fim_afazer_1" id="horario_fim_afazer_1" />
        </div>
        <div class="info">
          <label for="datas">Datas</label>
          <input type="date" name="data_afazer_1" id="data_afazer_1" />
        </div>

        <div class="info">
          <label for="aulas">Se desejar, insira descanso</label>
          <input type="text" name="titulo_hvago_1" id="titulo_hvago_1" />
        </div>
        <div class="info">
          <label for="aulas">Descrição</label>
          <input type="text" name="descricao_hvago_1" id="descricao_hvago_1" />
        </div>
        <div class="info">
          <label for="horario">Início</label>
          <input type="time" name="horario_inicio_hvago_1" id="horario_inicio_hvago_1" />
        </div>
        <div class="info">
          <label for="horario">Término</label>
          <input type="time" name="horario_fim_hvago_1" id="horario_fim_hvago_1" />
        </div>
        <div class="info">
          <label for="datas">Datas</label>
          <input type="date" name="data_hvago_1" id="data_hvago_1" />
        </div>



            <div class="v121_57">
                <input type="submit" name="login" id="contID" class="v140_119" value="">
                <label class="v121_59" for="contID">Continue</label>
            </div>

        </form>
        <div class="v109_3137"></div>
        <div class="v109_3138"></div>
        <div class="v109_3140"></div>
        <div class="v141_97"></div>
        <div class="v141_107">
            <div class="v141_108"></div>
            <div class="v141_109"></div>
        </div>
        <div class="v109_3751">
            <div class="v109_3752">
                <div class="v109_3753">
                    <div class="v109_3754"></div>
                    <div class="v109_3755"></div>
                    <div class="v109_3756"></div>
                    <div class="v109_3757"></div>
                </div><span class="v109_3758">Daily Schedule</span>
            </div>
        </div>
    </div>

    <fieldset>
    <legend>Select a maintenance drone:</legend>

    <div>
      <input type="radio" id="huey" name="drone" value="huey"
             checked>
      <label for="huey">Huey</label>
    </div>

    <div>
      <input type="radio" id="dewey" name="drone" value="dewey">
      <label for="dewey">Dewey</label>
    </div>

    <div>
      <input type="radio" id="louie" name="drone" value="louie">
      <label for="louie">Louie</label>
    </div>
</fieldset>
</body>

</html>

dailyschedule/templates/dailyschedule/materias.html
<section id="criar-crono1">
  <form class="crono-info1" action="{% url 'cronograma:criarMaterias' %}" method="post">
    {% csrf_token %}
    <div style="display:flex; gap:10px; flex-direction:column;">

        <div style="display:flex; gap:10px; margin-bottom:15px;">
            <div class="info">
              <label for="titulo_materia_1">Informe suas matérias</label>
              <input type="text" name="titulo_materia_1" id="titulo_materia_1" />
            </div>
            <div class="info">
              <label for="assunto_1">Assunto</label>
              <input type="text" name="assunto_1" id="assunto_1" />
            </div>
            <div class="info">
              <label for="aulas">Descrição</label>
              <input type="text" name="descricao_materia_1" id="descricao_materia_1" />
            </div>
            <div class="info">
              <label for="horario_inicio_materia_1">Início</label>
              <input type="time" name="horario_inicio_materia_1" id="horario_inicio_materia_1" />
            </div>
            <div class="info">
              <label for="horario">Término</label>
              <input type="time" name="horario_fim_materia_1" id="horario_fim_materia_1" />
            </div>
            <div class="info">
              <label for="datas">Datas</label>
              <input type="date" name="data_materia_1" id="data_materia_1" />
            </div><br/>

            <label id="add_address" onclick="addMatterLine()" style="font-size:50pt;">+</label>
        </div>

        <div id="adress" style="paddin:50px 50px;">

        </div>
         <!--<a class="btncont" href="#criar-crono"><button style="background-color:none;" type="submit">Salvar e continuar</button></a>-->
    </div>
        <button type="submit" class="btncont" >Salvar materias</button>
  </form>
</section>


<!--
<section id="criar-crono1">
  <form class="crono-info1">
    <div class="info">
      <label for="aulas">Informe suas matérias</label>
      <input type="text" name="aulas" id="desc" />
    </div>
    <div class="info">
      <label for="aulas">Assunto</label>
      <input type="text" name="aulas" id="desc" />
    </div>
    <div class="info">
      <label for="horario">Início</label>
      <input type="time" name="horario" id="horario" />
    </div>
    <div class="info">
      <label for="horario">Término</label>
      <input type="time" name="horario" id="horario" />
    </div>
    <div class="info">
      <label for="datas">Datas</label>
      <input type="date" name="datas" id="data" />
    </div>
    <a class="btncont" href="#criar-crono">Continuar</a>
  </form>
</section>
-->